[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
server = ["dep:axum", "dep:tokio", "dep:tower-http", "common/server"]

[dependencies]
domain = { path = "../../domain"}
common = { path = "../common", features = ["front"]}
serde_json = "1.*"
derive-new = "0.5.*"
gloo-net = {version = "0.2.*", default-features = false, features = ["json", "http"]}
# optional dependencies
axum = { version = "0.6.*", optional = true}
tokio = { version = "1.*", features = ["full"], optional = true}
tower-http = { version = "0.3.*", features = ["cors"], optional = true}

[dev-dependencies]
wasm-bindgen-test = "0.3.*"
rstest = { version = "0.15.*"}
