[package]
name = "presentation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
domain = { path = "../domain" }
frontend = { path = "../application/frontend" }
dioxus = { version = "0.2.4", features = ["web"] }
gloo-events = "^0.1"
gloo-utils = "^0.1"
log = "^0.4"
wasm-logger = "^0.2"

[dev-dependencies]
# Examples
time = { version = "^0.3", features = ["parsing", "macros"] }
thiserror = "^1"


[profile.release]
# less code to include into binary
panic = 'abort'
# optimization over all codebase ( better optimization, slower build )
codegen-units = 1
# optimization for size ( more aggressive )
opt-level = 'z'
# link time optimization using using whole-program analysis
lto = true
