[package]
name = "serverside"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
inmemory = []

[dependencies]
domain = { path = "../../domain", features = ["repo"] }
infrastructure = { path = "../../infrastructure"}
common = { path = "../common", features = ["server"]}
derive-new = "0.5.*"
axum = "0.6.*"
serde = { version = "1.*", features = ["derive"]}
tokio = { version = "1.*", features = ["full"]}
tower-http = { version = "0.3.*", features = ["cors"]}
sqlx = { version = "0.6.*", features = ["postgres", "runtime-tokio-native-tls"] }

[dev-dependencies]
pretty_assertions = "1.3.*"
rstest = { version = "0.15.*"}
assert_matches = "1.*"
serde_json = "1.*"
mime = "0.3.*"
tower = { version = "0.4.*"}
hyper = { version = "0.14.*", features = ["full"] }
mockall = "0.11.*"
once_cell = "1.16.*"

