[package]
name = "integration_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
server = ["dep:config", "dep:serverside", "dep:axum", "dep:tokio", "dep:tower-http", "dep:infrastructure"]

[dependencies]

# optional dependencies
config = { path = "../../config", optional = true}
serverside = { path = "../serverside", features = ["inmemory"], optional = true}
infrastructure = { path = "../../infrastructure", optional = true}
axum = { version = "0.6.*", optional = true}
tokio = { version = "1.*", features = ["full"], optional = true}
tower-http = { version = "0.3.*", features = ["cors"], optional = true}


[dev-dependencies]
pretty_assertions = "1.3.*"
domain = { path = "../../domain"}
common = { path = "../common", features = ["front"]}
frontend = { path = "../frontend", features = ["test_api"]}
wasm-bindgen-test = "0.3.*"
assert_matches = "1.*"